crm.crm_contact_type.*:
  type: config_entity
  label: 'Contact type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

crm.crm_relationship_type.*:
  type: config_entity
  label: 'CRM Relationship type'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    uuid:
      type: string
      label: 'UUID'
    contact_type_a:
      type: string
      label: 'Contact type A'
    contact_type_b:
      type: string
      label: 'Contact type B'
    label_b_a:
      type: string
      label: 'Label b a'
