crm_field.crm_location_type.*:
  type: config_entity
  label: Location Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

# Field storage.
field.storage_settings.crm_email:
  type: mapping
  label: Example storage settings
  mapping:
    foo:
      type: string
      label: Foo

# Field instance.
field.field_settings.crm_email:
  type: mapping
  label: Example field settings
  mapping:
    bar:
      type: string
      label: Bar

# Default value.
field.value.crm_email:
  type: mapping
  label: Default value
  mapping:
    email:
      type: email
      label: Email
    location_id:
      type: string
      label: Location
    primary:
      type: boolean
      label: Primary
    billing:
      type: boolean
      label: Billing
    hold:
      type: boolean
      label: Hold
    bulk:
      type: boolean
      label: Bulk
    hold_date:
      type: datetime
      label: Hold Date
    reset_date:
      type: datetime
      label: Reset Date

# Field widget.
field.widget.settings.crm_email:
  type: mapping
  label: Example widget settings
  mapping:
    foo:
      type: string
      label: Foo

# Field formatter.
field.formatter.settings.crm_email_default:
  type: mapping
  label: Example formatter settings
  mapping:
    foo:
      type: string
      label: Foo

crm_field.crm_phone_type.*:
  type: config_entity
  label: Phone Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

# Field storage.
field.storage_settings.crm_telephone:
  type: mapping
  label: Example storage settings
  mapping:
    foo:
      type: string
      label: Foo

# Field instance.
field.field_settings.crm_telephone:
  type: mapping
  label: Example field settings
  mapping:
    bar:
      type: string
      label: Bar

# Default value.
field.value.crm_telephone:
  type: mapping
  label: Default value
  mapping:
    phone:
      type: telephone
      label: Phone
    phone_ext:
      type: string
      label: Extension
    type:
      type: string
      label: Type
    location_id:
      type: string
      label: Location
    primary:
      type: boolean
      label: Primary
    billing:
      type: boolean
      label: Billing
    mobile_provider_id:
      type: string
      label: Mobile Provider

# Field widget.
field.widget.settings.crm_telephone:
  type: mapping
  label: Example widget settings
  mapping:
    foo:
      type: string
      label: Foo

# Field formatter.
field.formatter.settings.crm_telephone_default:
  type: mapping
  label: Example formatter settings
  mapping:
    foo:
      type: string
      label: Foo

# Field storage.
field.storage_settings.crm_external_identifier:
  type: mapping
  label: Example storage settings
  mapping:
    foo:
      type: string
      label: Foo

# Field instance.
field.field_settings.crm_external_identifier:
  type: mapping
  label: Example field settings
  mapping:
    bar:
      type: string
      label: Bar

# Default value.
field.value.crm_external_identifier:
  type: mapping
  label: Default value
  mapping:
    source:
      type: string
      label: Source
    identifier:
      type: string
      label: Identifier

# Field widget.
field.widget.settings.crm_external_identifier:
  type: mapping
  label: Example widget settings
  mapping:
    foo:
      type: string
      label: Foo

# Field formatter.
field.formatter.settings.crm_external_identifier_default:
  type: mapping
  label: Example formatter settings
  mapping:
    foo:
      type: string
      label: Foo

crm_field.crm_website_type.*:
  type: config_entity
  label: Website Type
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string

# Field storage.
field.storage_settings.crm_website:
  type: mapping
  label: Example storage settings
  mapping:
    foo:
      type: string
      label: Foo

# Field instance.
field.field_settings.crm_website:
  type: mapping
  label: Example field settings
  mapping:
    bar:
      type: string
      label: Bar

# Default value.
field.value.crm_website:
  type: mapping
  label: Default value
  mapping:
    url:
      type: uri
      label: Url
    type:
      type: string
      label: Type

# Field widget.
field.widget.settings.crm_website:
  type: mapping
  label: Example widget settings
  mapping:
    foo:
      type: string
      label: Foo

# Field formatter.
field.formatter.settings.crm_website_default:
  type: mapping
  label: Example formatter settings
  mapping:
    foo:
      type: string
      label: Foo
